### PR TITLE
Full async query model

### PR DESCRIPTION
**Pull request by taooceros**
Update plugin dependency
Use the new async model to make every query method async
Connect Sqlite with Read Only mode

### CODE REVIEW

**Review by harrynull — APPROVED** [review]
Looks great! Thanks.

**Comment by taooceros** [comment]
@harrynull I don't have the write access, so maybe you have to merge it and create an release.

**Comment by harrynull** [comment]
@taooceros All I have to do is making a new release, and new installs will use the latest release? Or do I need to update download link somewhere?

**Comment by taooceros** [comment]
Yeah you may need to update the download link and version for flow plugin manifest here https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest.

**Comment by harrynull** [comment]
Sounds good! Will do that after I finish with #5 .

**Comment by taooceros** [comment]
Great! Thank you!

**Pull request merged**
