### PR TITLE
Use " instead of ' to avoid potential ' exist in words

### PR DESCRIPTION
**Pull request by taooceros**

### CODE REVIEW

**Review by harrynull — APPROVED** [review]
It'd cause issues if the word contains " though, although it's more unlikely than '.
It would be better if I used parameterized query but I guess I was lazy when writing this.

**Comment by taooceros** [comment]
> It'd cause issues if the word contains " though, although it's more unlikely than '.
> It would be better if I used parameterized query but I guess I was lazy when writing this.

haha, what do you mean by parametrized query? I am not quite familiar with that.

**Comment by harrynull** [comment]
It's also called prepared statements
https://zetcode.com/csharp/sqlite/
this article might help.

**Comment by taooceros** [comment]
But I think that's a little bit hard to do for joining multiple possible results for the `in` clause

**Comment by taooceros** [comment]
I found that sqlite use `''` to escape `'`, maybe that's a better choice.

**Comment by harrynull** [comment]
Thanks! It looks great.

**Pull request merged**
