### PR TITLE
Use Null Access for save

### PR DESCRIPTION
**Pull request by taooceros**
in case settings is not initialized?
https://github.com/Flow-Launcher/Flow.Launcher/issues/1471

### CODE REVIEW

**Comment by harrynull** [comment]
I wonder in which case the settings would be not initialized. and what the implications might be when Save is not called.

**Comment by taooceros** [comment]
> I wonder in which case the settings would be not initialized. and what the implications might be when Save is not called.

I have no idea how this can happens. Everything is supposed to be called after Init (InitAsync), and I have never met that issue once. However the implication may be not so big, because I think the save is only about the API? However, it will not change unless user open the setting panel, which should always happen after Initialization so I think the implication is trivial.

**Comment by jjw24** [comment]
I am afk but squinting at my phone I see you have an InitAsync() and a save(), flow would call the save() on start up to save all loaded settings, and maybe the issue is the Settings class in your async init has not initialized yet.

If you are just loading normal settings file, what about using `settings = context.API.LoadSettingJsonStorage<Settings>();` and let flow handle saving settings. https://github.com/Flow-Launcher/Flow.Launcher/blob/43ac9b4f6d461525a3c1460dc042883befaa717f/Flow.Launcher.Plugin/Interfaces/IPublicAPI.cs#L212

**Comment by taooceros** [comment]
image
in either situation, they will not be null I think?

**Comment by taooceros** [comment]
Sorry i misunderstand the comment. I think that's unreasonable. Every call to the plugin function should happen after Init

**Comment by harrynull** [comment]
I took a closer look at the callstack and realized that Flow-Launcher/Flow.Launcher#1471 and Flow-Launcher/Flow.Launcher#1375 are different. The former happens when the user closes the Settings window (onClosed) so the settings should have been initialized (i.e. race conditions are unlikely I think?).

**Comment by harrynull** [comment]
I'm going to merge this one for now just to treat the symptom and hope that nothing terrible would happen but we probably want to dig out the root cause some time, or switch to that API to properly store settings (which could means that we have to add some migration logic).

**Comment by taooceros** [comment]
I agree. I will recently check in detail.

**Comment by taooceros** [comment]
Is it possible that this line `settings = (await JsonSerializer.DeserializeAsync<Settings>(fileStream).ConfigureAwait(false))!;` returns null?

**Comment by taooceros** [comment]
I check both callstack, and both of them should happen after plugin initialization.
1. Happens when close setting window
2. Happens after finishing all startup initialization

I don't know whether something went wrong here

**Comment by harrynull** [comment]
TIL "!" in C# does not throw an exception if the object is actually null 🤯 I always thought it would throw an NPE on the spot.

That said, I feel like that `JsonSerializer.DeserializeAsync` usually would just throw an exception if the json or the file stream is broken rather than returning a null but I don't know C# well enough to be sure about that.

**Comment by taooceros** [comment]
I think it should??? I haven't met any situation where it returns null instead of a valid object. Though that may be a possibility. We may need to check the doc about it.

**Pull request merged**
