### PR TITLE
Use separate connection with pooling for each function

### PR DESCRIPTION
**Pull request by taooceros**
QueryRange and QueryLike takes quite a bit of time when query string is short, so one connection is hard to handle them when typing fast.
With this build I can see the result pop out fluently, when I am typing quickly.
On the past, sometimes it takes quite a while to wait until the result pop up for latest query after typing a word.

I believe multiple connection help concurrent reading quite a lot. However, not sure whether it would be better to keep one connection per query or keep one connection per select, but I think using pool will be fine.

### CODE REVIEW

**Comment by harrynull** [comment]
That's interesting. I thought it'd take more time to open a new connection because of IO...

**Comment by taooceros** [comment]
> That's interesting. I thought it'd take more time to open a new connection because of IO...

I originally also think that will be the case, but after taking a trial, the result surprise me.
Also, I think the connection pool will overcome the issue of IO because it will maintain a few connections for us to reuse.

**Comment by harrynull** [comment]
Sorry I've been busy this week. I might review and merge it later this week or early next week.

**Comment by taooceros** [comment]
> Sorry I've been busy this week. I might review and merge it later this week or early next week.

No problem. 😉

**Review by harrynull — APPROVED** [review]
Haven't really tested yet but it looks great!
My guess is that System.Data.SQLite maintains some sort of connection pool internally and apparently the best practice is to keep the connection as short as possible.
Thanks for the PR and sorry for the late review.

**Pull request merged**
